<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AKAPOOR7450" name="Test(failed)" tests="2" failures="2" timestamp="29 Apr 2017 03:37:32 GMT" time="0.019" errors="0">
  <testcase name="Retry1" time="0.009" classname="Retry.RetryFailed">
    <failure type="java.lang.AssertionError" message="Failed expected [abc] but found [abc1]">
      <![CDATA[java.lang.AssertionError: Failed expected [abc] but found [abc1]
	at Retry.RetryFailed.Retry1(RetryFailed.java:23)
	at Retry.Runner.main(Runner.java:17)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Retry1 -->
  <testcase name="Retry" time="0.001" classname="Retry.RetryFailed">
    <failure type="java.lang.AssertionError" message="Failed expected [abc] but found [abc1]">
      <![CDATA[java.lang.AssertionError: Failed expected [abc] but found [abc1]
	at Retry.RetryFailed.Retry(RetryFailed.java:13)
	at Retry.Runner.main(Runner.java:17)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Retry -->
</testsuite> <!-- Test(failed) -->
